/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;


/**
 *
 * @author thesc
 */
public class ManagePropertyListing extends javax.swing.JPanel {
	JLabel propertyActivationLabel = new JLabel();

    /**
     * Creates new form ManageSpecificPropertyPage
     */
    public ManagePropertyListing() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel = new javax.swing.JLabel();
        priceTitleLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addressTitleLabel = new javax.swing.JLabel();
        addressLine1Label = new javax.swing.JLabel();
        propertyImageLabel = new javax.swing.JLabel();
        viewDetailsButton = new javax.swing.JButton();
        propertyNameLabel = new javax.swing.JLabel();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 200));
        //setResizable(false);

        projectNameLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        projectNameLabel.setText("Project name");

        priceTitleLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 14)); // NOI18N
        priceTitleLabel.setText("Price:");

        priceLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 14)); // NOI18N
        priceLabel.setText("price");

        addressTitleLabel.setText("Address:");

        addressLine1Label.setText("line 1");

        viewDetailsButton.setText("View details");
//        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                viewDetailsButtonActionPerformed(evt);
//            }
//        });

        propertyNameLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        propertyNameLabel.setText("Property name");
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(propertyImageLabel, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(projectNameLabel)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(addressLine1Label, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
        							.addGap(42)
        							.addComponent(priceTitleLabel)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(priceLabel))
        						.addComponent(propertyNameLabel)
        						.addComponent(addressTitleLabel))
        					.addPreferredGap(ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
        					.addComponent(viewDetailsButton, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        				.addComponent(propertyActivationLabel))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(propertyImageLabel, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(projectNameLabel)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(propertyNameLabel)
        							.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
        							.addComponent(propertyActivationLabel)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(addressTitleLabel)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        									.addComponent(priceTitleLabel)
        									.addComponent(priceLabel))
        								.addComponent(addressLine1Label, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(0, 146, Short.MAX_VALUE)
        							.addComponent(viewDetailsButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
        					.addContainerGap())))
        );
        setLayout(layout);

        //pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(ManagePropertyListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(ManagePropertyListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(ManagePropertyListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(ManagePropertyListing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new ManagePropertyListing().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JLabel addressTitleLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceTitleLabel;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JLabel propertyImageLabel;
    private javax.swing.JLabel propertyNameLabel;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JLabel getAddressLine1Label() {
        return addressLine1Label;
    }
    public javax.swing.JLabel getAddressTitleLabel() {
        return addressTitleLabel;
    }
    public javax.swing.JLabel getPriceLabel() {
        return priceLabel;
    }
    public javax.swing.JLabel getPriceTitleLabel() {
        return priceTitleLabel;
    }
    public javax.swing.JLabel getProjectNameLabel() {
        return projectNameLabel;
    }
    public javax.swing.JLabel getPropertyImageLabel() {
        return propertyImageLabel;
    }
    public javax.swing.JLabel getPropertyNameLabel() {
        return propertyNameLabel;
    }
    public JLabel getPropertyActivationLabel() {
    	return propertyActivationLabel;
    }
    public javax.swing.JButton getViewDetailsButton() {
        return viewDetailsButton;
    }
}
