import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thesc
 */
public class ManagePropertiesPage extends javax.swing.JPanel {
	 private JPanel panelInsideScrollPane;
	 private ArrayList<JButton> viewDetailsButtons = new ArrayList<>();

    /**
     * Creates new form ManagePropertiesPage
     */
    public ManagePropertiesPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        sideBarPanel.setBounds(0, 0, 246, 746);
        sidebarPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        rentRequestsButton = new javax.swing.JButton();
        managePropertiesButton = new javax.swing.JButton();
        myPropertiesLabel = new javax.swing.JLabel();
        newPropertyPageButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        titleLabel.setBounds(252, 11, 276, 33);
        requestsScrollPane = new javax.swing.JScrollPane();
        requestsScrollPane.setBounds(252, 62, 750, 600);

        setSize(new java.awt.Dimension(1024, 700));

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 700));
        //setResizable(false);

        sideBarPanel.setPreferredSize(new java.awt.Dimension(255, 684));

        sidebarPanel.setBackground(new java.awt.Color(204, 0, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(255, 684));

        homeButton.setBackground(new java.awt.Color(204, 0, 0));
        homeButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setBorder(null);

        rentRequestsButton.setBackground(new java.awt.Color(204, 0, 0));
        rentRequestsButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        rentRequestsButton.setForeground(new java.awt.Color(255, 255, 255));
        rentRequestsButton.setText("Rent requests");
        rentRequestsButton.setBorder(null);
        // rentRequestsButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         rentRequestsButtonActionPerformed(evt);
        //     }
        // });

        managePropertiesButton.setBackground(new java.awt.Color(204, 0, 0));
        managePropertiesButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        managePropertiesButton.setForeground(new java.awt.Color(255, 255, 255));
        managePropertiesButton.setText("Manage Properties");
        managePropertiesButton.setBorder(null);
        // managePropertiesButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         managePropertiesButtonActionPerformed(evt);
        //     }
        // });

        myPropertiesLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 14)); // NOI18N
        myPropertiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        myPropertiesLabel.setText("My Properties");

        newPropertyPageButton.setBackground(new java.awt.Color(204, 0, 0));
        newPropertyPageButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        newPropertyPageButton.setForeground(new java.awt.Color(255, 255, 255));
        newPropertyPageButton.setText("New Property");
        newPropertyPageButton.setBorder(null);
        // newPropertyPageButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         newPropertyPageButtonActionPerformed(evt);
        //     }
        // });

        logOutButton.setBackground(new java.awt.Color(204, 0, 0));
        logOutButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setBorder(null);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPropertyPageButton)
                            .addComponent(managePropertiesButton)))
                    .addComponent(myPropertiesLabel)
                    .addComponent(rentRequestsButton)
                    .addComponent(logOutButton)
                    .addComponent(homeButton))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeButton)
                .addGap(18, 18, 18)
                .addComponent(rentRequestsButton)
                .addGap(18, 18, 18)
                .addComponent(myPropertiesLabel)
                .addGap(18, 18, 18)
                .addComponent(managePropertiesButton)
                .addGap(18, 18, 18)
                .addComponent(newPropertyPageButton)
                .addGap(38, 38, 38)
                .addComponent(logOutButton)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 24)); // NOI18N
        titleLabel.setText("Manage Properties");
        titleLabel.setPreferredSize(new java.awt.Dimension(276, 33));
        titleLabel.setRequestFocusEnabled(false);
        
        
        
        
        panelInsideScrollPane = new JPanel();
		panelInsideScrollPane.setPreferredSize(new Dimension(400,400));
        requestsScrollPane = new JScrollPane(panelInsideScrollPane,
                JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
                JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        requestsScrollPane.getVerticalScrollBar().setUnitIncrement(16);
//		panelInsideScrollPane.setPreferredSize(new Dimension(800,400));
//       requestScrollPane.setViewportView(panel);
		panelInsideScrollPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
//		panelInsideScrollPane.add(new JPanel());
		requestsScrollPane.setLocation(247, 82);
		requestsScrollPane.setSize(761, 575);
		setLayout(null);
        add(sideBarPanel);
        add(titleLabel);
        add(requestsScrollPane);
        //pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setPropertiesList(ArrayList<ManagePropertyListing> managePropertyListing) {
		panelInsideScrollPane.removeAll();
		viewDetailsButtons.clear();
//		denyButtons.clear();
//		propertiesViewDetailsButtons.clear();
		if(managePropertyListing.size() == 0) {
//			noResultFoundMessage();
		}
//		ArrayList<ManagePropertyListing> instances = new ArrayList<>();
		for(int i = 0; i < managePropertyListing.size(); i++){
//			ManagePropertyListing instance = new ManagePropertyListing();
			
//			instance.getProjectNameLabel().setText(propertyList.get(i).getPropertyAddress().getProject());
//			instance.getPropertyNameLabel().setText(propertyList.get(i).getTitileName());
//			instance.getPropertyActivationLabel().setText(propertyList.get(i).getPropertyActivationStatus());
//			instance.getAddressLine1Label().setText(propertyList.get(i).getPropertyAddress().getFullAddress());
//			instance.getPriceLabel().setText(Double.toString(propertyList.get(i).getPrice()));
//			instance.getPropertyImageLabel().setIcon(loadImage(managePropertyListing.get(i).getPropertyPicturePath()[0], 121,189));
			//			JPanel panel = new JPanel();
//			propertyList.get(i).setBackground(Color.white);
//			add(requestsList.get(i));
//			panel.setBackground(Color.WHITE);
//			viewDetailsButtons.add(propertyList.get(i).getViewDetailsButton());
//			denyButtons.add(requestsList.get(i).getDenyRequestButton());
			
//			requestsList.get(i).setPreferredSize(new Dimension(800,400));
//			requestsList.get(i).setLayout(null);
//			instances.add(instance);
//			JButton button = new JButton();
//			button.setBackground(new Color(255,240,149));
//			button.setFocusable(false);
//			button.setBounds(565, 329, 165, 40);
//			instance.add(button);
//			if()
//			managePropertyListing.get(i).setBackground(Color.LIGHT_GRAY);
			viewDetailsButtons.add(managePropertyListing.get(i).getViewDetailsButton());
			
			panelInsideScrollPane.setPreferredSize(new Dimension(800,300 * (i+1)));
			panelInsideScrollPane.add(managePropertyListing.get(i));
		}
	}

    private void newPropertyPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPropertyPageButtonActionPerformed
        // TODO add your handling code here:
        new NewPropertyPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_newPropertyPageButtonActionPerformed

    private void managePropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePropertiesButtonActionPerformed
        // TODO add your handling code here:
        new ManagePropertiesPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_managePropertiesButtonActionPerformed

    private void rentRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentRequestsButtonActionPerformed
        // TODO add your handling code here:
        new ManagePropertiesPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_rentRequestsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         // for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //         //     if ("Nimbus".equals(info.getName())) {
    //         //         javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //         //         break;
    //         //     }
    //         // }
    //         new ManagePropertiesPage();
    //     } catch (Exception ex) {
    //         java.util.logging.Logger.getLogger(ManagePropertiesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } 
    //     //catch (InstantiationException ex) {
    //     //     java.util.logging.Logger.getLogger(ManagePropertiesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     // } catch (IllegalAccessException ex) {
    //     //     java.util.logging.Logger.getLogger(ManagePropertiesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //     //     java.util.logging.Logger.getLogger(ManagePropertiesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     // }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new ManagePropertiesPage().setVisible(true);
    //         }
    //     });
    // }
    private ImageIcon loadImage(String path, int x, int y){
        Image image = new ImageIcon(this.getClass().getResource(path)).getImage();
        Image scaledImage = image.getScaledInstance(x, y, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(scaledImage);
	} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton managePropertiesButton;
    private javax.swing.JLabel myPropertiesLabel;
    private javax.swing.JButton newPropertyPageButton;
    private javax.swing.JButton rentRequestsButton;
    private javax.swing.JScrollPane requestsScrollPane;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JButton getHomeButton() {
        return homeButton;
    }
    public javax.swing.JButton getLogOutButton() {
        return logOutButton;
    }
    public javax.swing.JButton getManagePropertiesButton() {
        return managePropertiesButton;
    }
    public javax.swing.JLabel getMyPropertiesLabel() {
        return myPropertiesLabel;
    }
    public javax.swing.JButton getNewPropertyPageButton() {
        return newPropertyPageButton;
    }
    public javax.swing.JButton getRentRequestsButton() {
        return rentRequestsButton;
    }
    public javax.swing.JScrollPane getRequestsScrollPane() {
        return requestsScrollPane;
    }
    public javax.swing.JPanel getSidebarPanel() {
        return sidebarPanel;
    }
    public javax.swing.JPanel getSideBarPanel() {
        return sideBarPanel;
    }
    public javax.swing.JLabel getTitleLabel() {
        return titleLabel;
    }
    public ArrayList<JButton> getViewDetailsButtons(){
    	return viewDetailsButtons;
    }
}
