import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thesc
 */
public class NewPropertyPage extends javax.swing.JPanel {
    

    /**
     * Creates new form NewPropertyPage
     */
    public NewPropertyPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        rentRequestsButton = new javax.swing.JButton();
        managePropertiesButton = new javax.swing.JButton();
        myPropertiesLabel = new javax.swing.JLabel();
        newPropertyPageButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        selectProjectLabel = new javax.swing.JLabel();
        propertyNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        featureLabel = new javax.swing.JLabel();
        facilityLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        bedsLabel = new javax.swing.JLabel();
        bathsLabel = new javax.swing.JLabel();
        propertyTypeLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        propertyTypeComboBox = new javax.swing.JComboBox<>();
        descScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        airConditionerCheckBox = new javax.swing.JCheckBox();
        kitchenCabinetCheckBox = new javax.swing.JCheckBox();
        gardenCheckBox = new javax.swing.JCheckBox();
        garageCheckBox = new javax.swing.JCheckBox();
        securityCheckBox = new javax.swing.JCheckBox();
        parkingCheckBox = new javax.swing.JCheckBox();
        supermarketCheckBox = new javax.swing.JCheckBox();
        gymCheckBox = new javax.swing.JCheckBox();
        playgroundCheckBox = new javax.swing.JCheckBox();
        projectComboBox = new javax.swing.JComboBox<>();
        sizeTextField = new javax.swing.JTextField();
        bedsComboBox = new javax.swing.JComboBox<>();
        bathsComboBox = new javax.swing.JComboBox<>();
        addImagesButton = new javax.swing.JButton();
        poolCheckBox = new javax.swing.JCheckBox();
        sportCheckBox = new javax.swing.JCheckBox();
        projectNameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        furnishingLabel = new javax.swing.JLabel();
        furnishingComboBox = new javax.swing.JComboBox<>();

        sidebarPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        rentRequestsButton = new javax.swing.JButton();
        managePropertiesButton = new javax.swing.JButton();
        myPropertiesLabel = new javax.swing.JLabel();
        newPropertyPageButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        selectProjectLabel = new javax.swing.JLabel();
        propertyNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        featureLabel = new javax.swing.JLabel();
        facilityLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        bedsLabel = new javax.swing.JLabel();
        bathsLabel = new javax.swing.JLabel();
        propertyTypeLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        propertyTypeComboBox = new javax.swing.JComboBox<>();
        descScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        airConditionerCheckBox = new javax.swing.JCheckBox();
        kitchenCabinetCheckBox = new javax.swing.JCheckBox();
        gardenCheckBox = new javax.swing.JCheckBox();
        garageCheckBox = new javax.swing.JCheckBox();
        securityCheckBox = new javax.swing.JCheckBox();
        parkingCheckBox = new javax.swing.JCheckBox();
        supermarketCheckBox = new javax.swing.JCheckBox();
        gymCheckBox = new javax.swing.JCheckBox();
        playgroundCheckBox = new javax.swing.JCheckBox();
        projectComboBox = new javax.swing.JComboBox<>();
        sizeTextField = new javax.swing.JTextField();
        bedsComboBox = new javax.swing.JComboBox<>();
        bathsComboBox = new javax.swing.JComboBox<>();
        addImagesButton = new javax.swing.JButton();
        poolCheckBox = new javax.swing.JCheckBox();
        sportCheckBox = new javax.swing.JCheckBox();
        projectNameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        furnishingLabel = new javax.swing.JLabel();
        furnishingComboBox = new javax.swing.JComboBox<>();

        setSize(new java.awt.Dimension(1024, 700));

        // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        // setResizable(false);

        sidebarPanel.setBackground(new java.awt.Color(204, 0, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(255, 684));

        homeButton.setBackground(new java.awt.Color(204, 0, 0));
        homeButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setBorder(null);
        // homeButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         homeButtonActionPerformed(evt);
        //     }
        // });

        rentRequestsButton.setBackground(new java.awt.Color(204, 0, 0));
        rentRequestsButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        rentRequestsButton.setForeground(new java.awt.Color(255, 255, 255));
        rentRequestsButton.setText("Rent requests");
        rentRequestsButton.setBorder(null);
        // rentRequestsButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         rentRequestsButtonActionPerformed(evt);
        //     }
        // });

        managePropertiesButton.setBackground(new java.awt.Color(204, 0, 0));
        managePropertiesButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        managePropertiesButton.setForeground(new java.awt.Color(255, 255, 255));
        managePropertiesButton.setText("Manage Properties");
        managePropertiesButton.setBorder(null);
        // managePropertiesButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         managePropertiesButtonActionPerformed(evt);
        //     }
        // });

        myPropertiesLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 14)); // NOI18N
        myPropertiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        myPropertiesLabel.setText("My Properties");

        newPropertyPageButton.setBackground(new java.awt.Color(204, 0, 0));
        newPropertyPageButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        newPropertyPageButton.setForeground(new java.awt.Color(255, 255, 255));
        newPropertyPageButton.setText("New Property");
        newPropertyPageButton.setBorder(null);
        // newPropertyPageButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         newPropertyPageButtonActionPerformed(evt);
        //     }
        // });

        logOutButton.setBackground(new java.awt.Color(204, 0, 0));
        logOutButton.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setBorder(null);
        // logOutButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         logOutButtonActionPerformed(evt);
        //     }
        // });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPropertyPageButton)
                            .addComponent(managePropertiesButton)))
                    .addComponent(myPropertiesLabel)
                    .addComponent(rentRequestsButton)
                    .addComponent(logOutButton)
                    .addComponent(homeButton))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeButton)
                .addGap(18, 18, 18)
                .addComponent(rentRequestsButton)
                .addGap(18, 18, 18)
                .addComponent(myPropertiesLabel)
                .addGap(18, 18, 18)
                .addComponent(managePropertiesButton)
                .addGap(18, 18, 18)
                .addComponent(newPropertyPageButton)
                .addGap(38, 38, 38)
                .addComponent(logOutButton)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Source Serif Pro Black", 0, 24)); // NOI18N
        titleLabel.setText("New Property");

        selectProjectLabel.setText("Select project:");

        propertyNameLabel.setText("Property name:");

        priceLabel.setText("Price(RM):");

        descLabel.setText("Description:");

        featureLabel.setText("Features:");

        facilityLabel.setText("Facilities:");

        sizeLabel.setText("Size (sq ft. ):");

        bedsLabel.setText("Bedrooms:");

        bathsLabel.setText("Bathrooms:");

        propertyTypeLabel.setText("Property type:");

        addButton.setText("Add property");
        // addButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         addButtonActionPerformed(evt);
        //     }
        // });

        nameTextField.setToolTipText("Enter property name");
        // nameTextField.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         nameTextFieldActionPerformed(evt);
        //     }
        // });

        priceTextField.setToolTipText("Enter price");

        propertyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartment", "Flat", "Condominium", "Serviced Residence", "Link House", "Cluster House", "Bungalow", "Semi-Detached House", "Villa", "Residentia lLand" }));
        // propertyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         propertyTypeComboBoxActionPerformed(evt);
        //     }
        // });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Enter description");
        descScrollPane.setViewportView(jTextArea1);

        airConditionerCheckBox.setText("Air Conditioner");
        airConditionerCheckBox.setMaximumSize(new java.awt.Dimension(369, 219));
        airConditionerCheckBox.setMinimumSize(new java.awt.Dimension(369, 219));

        kitchenCabinetCheckBox.setText("Kitchen Cabinet");
        // kitchenCabinetCheckBox.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         kitchenCabinetCheckBoxActionPerformed(evt);
        //     }
        // });

        gardenCheckBox.setText("Garden");

        garageCheckBox.setText("Garage");

        securityCheckBox.setText("24-Hour Security");

        parkingCheckBox.setText("Parking");

        supermarketCheckBox.setText("Supermarket");

        gymCheckBox.setText("Gym");

        playgroundCheckBox.setText("Playground");

        try{    
            File projectsNamesFile = new File("src/System/Property Manager/Projects.txt");
            java.util.Scanner projectsNamesFileScannner = new java.util.Scanner(projectsNamesFile);
            while(projectsNamesFileScannner.hasNext())
                projectComboBox.addItem(projectsNamesFileScannner.nextLine());
            projectComboBox.addItem("New Project");
        }catch(Exception ex) {
            ex.printStackTrace();
        }

        //projectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" })); //Item List

        sizeTextField.setToolTipText("Enter size");

        bedsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10+" }));

        bathsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10+" }));

        addImagesButton.setText("Add Images");
        // addImagesButton.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         addImagesButtonActionPerformed(evt);
        //     }
        // });

        poolCheckBox.setText("Swimming Pool");

        sportCheckBox.setText("Sport Court");

        projectNameTextField.setToolTipText("Enter project name");
        projectNameTextField.setVisible(false);
        // projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         projectNameTextFieldActionPerformed(evt);
        //     }
        // });

        addressLabel.setText("Address:");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        furnishingLabel.setText("Furnishing:");

        furnishingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Furnished", "Partially Furnished", "Unfurnished", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(propertyNameLabel)
                                    .addComponent(priceLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(titleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sizeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(propertyTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(propertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(featureLabel)
                            .addComponent(airConditionerCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilityLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bedsLabel)
                                .addGap(8, 8, 8)
                                .addComponent(bedsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(descScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectProjectLabel)
                                    .addComponent(addressLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(descLabel)
                                    .addGap(217, 217, 217)
                                    .addComponent(furnishingLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(furnishingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(securityCheckBox)
                                        .addComponent(poolCheckBox))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(kitchenCabinetCheckBox)
                                            .addGap(8, 8, 8)
                                            .addComponent(gardenCheckBox))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sportCheckBox)
                                                .addComponent(parkingCheckBox))
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(gymCheckBox)
                                                .addComponent(supermarketCheckBox))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(garageCheckBox)
                                        .addComponent(playgroundCheckBox)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bathsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bathsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(51, 51, 51)
                        .addComponent(addImagesButton)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectProjectLabel)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(propertyNameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceLabel))
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertyTypeLabel)
                    .addComponent(propertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(furnishingLabel)
                    .addComponent(furnishingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(descScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(featureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airConditionerCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitchenCabinetCheckBox)
                    .addComponent(gardenCheckBox)
                    .addComponent(garageCheckBox))
                .addGap(23, 23, 23)
                .addComponent(facilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityCheckBox)
                    .addComponent(parkingCheckBox)
                    .addComponent(gymCheckBox)
                    .addComponent(playgroundCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poolCheckBox)
                    .addComponent(sportCheckBox)
                    .addComponent(supermarketCheckBox))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedsLabel)
                    .addComponent(bedsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathsLabel)
                    .addComponent(bathsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(addImagesButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        //this.setVisible(true); 

        //pack();
    }
    // </editor-fold>//GEN-END:initComponents

    // private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    //     // TODO add your handling code here:
    //     new ManagePropertiesPage().setVisible(true);
    //     setVisible(false);
    // }//GEN-LAST:event_addButtonActionPerformed

    // private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
    //     // TODO add your handling code here:
    // }//GEN-LAST:event_nameTextFieldActionPerformed

    // private void addImagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImagesButtonActionPerformed
    //     // TODO add your handling code here:
    //     new ManagePropertiesPage().setVisible(true);
    //     setVisible(false);
    // }//GEN-LAST:event_addImagesButtonActionPerformed

    // private void propertyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyTypeComboBoxActionPerformed
    //     // TODO add your handling code here:
    // }//GEN-LAST:event_propertyTypeComboBoxActionPerformed

    // private void kitchenCabinetCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenCabinetCheckBoxActionPerformed
    //     // TODO add your handling code here:
    // }//GEN-LAST:event_kitchenCabinetCheckBoxActionPerformed

    // private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
    //     // TODO add your handling code here:
    // }//GEN-LAST:event_projectNameTextFieldActionPerformed

    // private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
    //     // TODO add your handling code here:
        
    // }//GEN-LAST:event_homeButtonActionPerformed

    // private void rentRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentRequestsButtonActionPerformed
    //     // TODO add your handling code here:
    //     new RentRequestsPage().setVisible(true);
    //     setVisible(false);
    // }//GEN-LAST:event_rentRequestsButtonActionPerformed

    // private void managePropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePropertiesButtonActionPerformed
    //     // TODO add your handling code here:
    //     new ManagePropertiesPage().setVisible(true);
    //     setVisible(false);
    // }//GEN-LAST:event_managePropertiesButtonActionPerformed

    // private void newPropertyPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPropertyPageButtonActionPerformed
    //     // TODO add your handling code here:
    //     new NewPropertyPage().setVisible(true);
    //     setVisible(false);
    // }//GEN-LAST:event_newPropertyPageButtonActionPerformed

    // private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
    //     // TODO add your handling code here:
    // }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // try {
        //     new NewPropertyPage();


        //     // for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //     //     if ("Nimbus".equals(info.getName())) {
        //     //         javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //     //         break;
        //     //     }
        //     // }
        // } catch (Exception ex) {
        //     System.out.println(ex);
        //    // java.util.logging.Logger.getLogger(NewPropertyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // // } catch (InstantiationException ex) {
        // //     java.util.logging.Logger.getLogger(NewPropertyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // // } catch (IllegalAccessException ex) {
        // //     java.util.logging.Logger.getLogger(NewPropertyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        // //     java.util.logging.Logger.getLogger(NewPropertyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // // }
        // //</editor-fold>
        // }

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 NewPropertyPage np = new NewPropertyPage();
                 np.setSize(1024, 700);
                 np.setVisible(true);
             }
         });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JCheckBox airConditionerCheckBox;
    private javax.swing.JComboBox<String> bathsComboBox;
    private javax.swing.JLabel bathsLabel;
    private javax.swing.JComboBox<String> bedsComboBox;
    private javax.swing.JLabel bedsLabel;
    private javax.swing.JButton addImagesButton;
    private javax.swing.JLabel descLabel;
    private javax.swing.JScrollPane descScrollPane;
    private javax.swing.JLabel featureLabel;
    private javax.swing.JLabel facilityLabel;
    private javax.swing.JCheckBox garageCheckBox;
    private javax.swing.JCheckBox gardenCheckBox;
    private javax.swing.JCheckBox gymCheckBox;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox kitchenCabinetCheckBox;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton managePropertiesButton;
    private javax.swing.JLabel myPropertiesLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton newPropertyPageButton;
    private javax.swing.JCheckBox parkingCheckBox;
    private javax.swing.JCheckBox playgroundCheckBox;
    private javax.swing.JCheckBox poolCheckBox;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JComboBox<String> projectComboBox;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel propertyNameLabel;
    private javax.swing.JComboBox<String> propertyTypeComboBox;
    private javax.swing.JLabel propertyTypeLabel;
    private javax.swing.JButton rentRequestsButton;
    private javax.swing.JCheckBox securityCheckBox;
    private javax.swing.JLabel selectProjectLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JCheckBox sportCheckBox;
    private javax.swing.JCheckBox supermarketCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> furnishingComboBox;
    private javax.swing.JLabel furnishingLabel;
    




    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getAddButton() {
        return addButton;
    }
    public javax.swing.JButton getHomeButton() {
        return homeButton;
    }
    public javax.swing.JButton getaddImagesButton() {
        return addImagesButton;
    }
    public javax.swing.JButton getLogOutButton() {
        return logOutButton;
    }
    public javax.swing.JButton getRentRequestsButton() {
        return rentRequestsButton;
    }
    public javax.swing.JButton getNewPropertyPageButton() {
        return newPropertyPageButton;
    }
    public javax.swing.JButton getManagePropertiesButton() {
        return managePropertiesButton;
    }
    public javax.swing.JLabel getBedsLabel() {
        return bedsLabel;
    }
    public javax.swing.JLabel getDescLabel() {
        return descLabel;
    }
    public javax.swing.JLabel getSizeLabel() {
        return sizeLabel;
    }
    public javax.swing.JLabel getBathsLabel() {
        return bathsLabel;
    }
    public javax.swing.JLabel getPriceLabel() {
        return priceLabel;
    }
    public javax.swing.JLabel getTitleLabel() {
        return titleLabel;
    }
    public javax.swing.JLabel getAddressLabel() {
        return addressLabel;
    }
    public javax.swing.JLabel getFacilitiesLabel() {
        return facilityLabel;
    }
    public javax.swing.JLabel getFeaturesLabel() {
        return featureLabel;
    }
    public javax.swing.JLabel getMyPropertiesLabel() {
        return myPropertiesLabel;
    }
    public javax.swing.JLabel getPropertyNameLabel() {
        return propertyNameLabel;
    }
    public javax.swing.JLabel getPropertyTypeLabel() {
        return propertyTypeLabel;
    }
    public javax.swing.JLabel getSelectProjectLabel() {
        return selectProjectLabel;
    }
    public javax.swing.JCheckBox getGymCheckBox() {
        return gymCheckBox;
    }
    public javax.swing.JCheckBox getPoolCheckBox() {
        return poolCheckBox;
    }
    public javax.swing.JCheckBox getSportCheckBox() {
        return sportCheckBox;
    }
    public javax.swing.JCheckBox getGarageCheckBox() {
        return garageCheckBox;
    }
    public javax.swing.JCheckBox getGardenCheckBox() {
        return gardenCheckBox;
    }
    public javax.swing.JCheckBox getParkingCheckBox() {
        return parkingCheckBox;
    }
    public javax.swing.JCheckBox getSecurityCheckBox() {
        return securityCheckBox;
    }
    public javax.swing.JCheckBox getPlaygroundCheckBox() {
        return playgroundCheckBox;
    }
    public javax.swing.JCheckBox getSupermarketCheckBox() {
        return supermarketCheckBox;
    }
    public javax.swing.JCheckBox getAirConditionerCheckBox() {
        return airConditionerCheckBox;
    }
    public javax.swing.JCheckBox getKitchenCabinetCheckBox() {
        return kitchenCabinetCheckBox;
    }
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }
    public javax.swing.JTextField getNameTextField() {
        return nameTextField;
    }
    public javax.swing.JTextField getSizeTextField() {
        return sizeTextField;
    }
    public javax.swing.JTextField getPriceTextField() {
        return priceTextField;
    }
    public javax.swing.JTextArea getAddressTextArea() {
        return addressTextArea;
    }
    public javax.swing.JTextField getProjectNameTextField() {
        return projectNameTextField;
    }
    public javax.swing.JComboBox<String> getBedsComboBox() {
        return bedsComboBox;
    }
    public javax.swing.JComboBox<String> getBathsComboBox() {
        return bathsComboBox;
    }
    public javax.swing.JComboBox<String> getProjectComboBox() {
        return projectComboBox;
    }
    public javax.swing.JComboBox<String> getPropertyTypeComboBox() {
        return propertyTypeComboBox;
    }
    public javax.swing.JPanel getSidebarPanel() {
        return sidebarPanel;
    }
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    public javax.swing.JScrollPane getDescScrollPane() {
        return descScrollPane;
    }
    public javax.swing.JComboBox<String> getFurnishingComboBox() {
        return furnishingComboBox;
    }
    public javax.swing.JLabel getFurnishingLabel() {
        return furnishingLabel;
    }
    
}
